name             'automagic'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures automagic'
long_description 'Installs/Configures automagic'
version          '0.1.0'

depends 'mysql'
depends 'nginx'
depends 'php-fpm'
depends 'wordpress_nginx'
depends 'mysql-chef_gem', '>= 0.0.2'
depends 'database', '>= 1.6.0'
