---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[automagic-base]
      - recipe[automagic]
    attributes:
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      s3cmd:
        users:
          - root
          - vagrant
          - kitchen
