#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'
cookbook 'vim'
cookbook 'user',
	:git => 'git://github.com/fnichol/chef-user.git', :ref => 'v0.3.0'
cookbook 'sudo'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'
cookbook 'wordpress'
cookbook 'memcached'
