name             'automagic-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures automagic-base'
long_description 'Installs/Configures automagic-base'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'vim'
depends 'user'
depends 'sudo'
depends 'brightbox-ruby'
depends 'pure-ftpd'
